### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by brianpartridge** [thoughtbot/BOTNetworkActivityIndicator#2]
- (void)popNetowrkActivity;
  should be
- (void)popNetworkActivity;

**Comment by keith** [comment]
Fixed in https://github.com/thoughtbot/BOTNetworkActivityIndicator/pull/4

**Comment by brianpartridge** [comment]
Nice.

**Comment by aufflick** [comment]
Any chance someone could push the 1.0.1 podspec to the CocoaPods master? Still only has 1.0.0.
