### ISSUE TITLE
Counter bug

### ISSUE THREAD

**Issue by brianpartridge** [thoughtbot/BOTNetworkActivityIndicator#3]
You're using NSUInteger but then comparing it > 0. I think this needs 2 changes: 
- Assert if pop is called when the counter is already 0. This should be caught during development/testing by callers. 
- Either switch to NSInteger or change the comparison to != 0

**Comment by keith** [comment]
Thanks! Checkout this PR that should fix this https://github.com/thoughtbot/BOTNetworkActivityIndicator/pull/4
